FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]

EXPOSE 80

#RUN chmod -R 100 $(pwd)/Dockerfile_scripts.sh && \ 
#    $(pwd)/Dockerfile_scripts.sh

